# -*- coding: utf-8 -*-
"""week8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HvgbW7oEw3B6gK-bGFo5Cma4shtNqjsk
"""

!pip install -q streamlit

import streamlit as st

st.title("Find the largest among the 3 numbers")
a=st.number_input("Enter number 1")
b=st.number_input("Enter number 2")
c=st.number_input("Enter number 3")
cal=st.button("Find the largest number")

def lar_num(a,b,c):
  if a>b and a>c:
    return a
  elif b>a and b>c:
    return b
  else:
    return c
if cal:
  larg_num=lar_num(a,b,c)
  st.write("The largest number is:",larg_num)